RBBE-corp/twobyfour

app/models/score.rb, db/migrate/20220210125646_create_scores.rb, test/models/score_test.rb
=> score model created

app/controllers/users_controller.rb, config/routes.rb, test/controllers/users_controller_test.rb
=> User controller

app/models/user.rb
User table validation for username
=> user validation done

Gemfile.lock, app/models/playlist.rb, app/models/playlist_entry.rb
playlist validations and playlist-entry validations
=> made playlist validations and playlist entry validations

app/models/user.rb
=> user table association

app/models/user.rb
destroy all compositions and playlists if user is destroyed.
=> dependent_destroy_for_user

app/controllers/playlist_entrys_controller.rb, app/controllers/playlists_controller.rb, config/routes.rb, test/controllers/playlist_entrys_controller_test.rb, test/controllers/playlists_controller_test.rb
controller and routes for playlist and playlist entries.
=> controller and routes for playlist and playlist entries.

app/views/playlists/edit.html.erb, app/views/playlists/index.html.erb, app/views/playlists/new.html.erb, app/views/playlists/show.html.erb, config/routes.rb
basic and functional show/index/edit playlists
new is there but functionality not yet
=> basic and functional show/index/edit playlists

app/controllers/users_controller.rb, app/models/composition.rb, app/models/user.rb, app/views/users/profile.html.erb
User profile page and added avg_score for user.
=> User profile

app/controllers/scores_controller.rb, app/models/flashcard.rb, app/models/memory_list.rb, app/models/memory_list_flashcard.rb, db/schema.rb, db/seeds.rb
Added all the flashcards necessary for Saturday's demo
Naming for Scores controller and associated directory has been fixed as well.
=> Seeds updated with new flashcards

app/views/compositions/index.html.erb, app/views/compositions/show.html.erb, app/views/shared/_navbar.html.erb
I changed naming for some of the composition show buttons but there should be no confllict
=> added links to navbar

app/controllers/users_controller.rb, app/models/user.rb, app/views/compositions/index.html.erb, app/views/shared/_navbar.html.erb, app/views/users/profile.html.erb
It needs some more cleaning especially for the flashcards but I couldn't retrieve the flashcards through memorylist flashcards so if would be great if some on can handle that part.
=> Views overhaul

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_range-slider.scss, app/javascript/components/files_player.js, app/javascript/components/range_slider.js, app/javascript/packs/application.js, app/views/compositions/show.html.erb
added one volume slider but not connected to audio right now, styling not there either
=> added one volume slider but not connected to any audio right now

app/assets/config/manifest.js, db/schema.rb
=> manifest problem

app/views/compositions/show.html.erb
=> composition style

app/assets/stylesheets/components/_composition_card.scss, app/assets/stylesheets/components/_index.scss, app/models/instrumental.rb, app/views/users/profile.html.erb
composition cards done / duration_in_min method done / name link to show
=> Profile composition cards

app/views/components/_composition-card.html.erb, app/views/users/profile.html.erb
Just moved composition card into partial
=> composition card in partial

app/assets/stylesheets/pages/_composition_show.scss, app/assets/stylesheets/pages/_index.scss, app/javascript/components/composition_player.js, app/javascript/components/composition_stop_player.js, app/javascript/components/files_player.js, app/javascript/packs/application.js, app/views/compositions/show.html.erb, db/schema.rb
composition show (play/pause and stop)
=> Composition show playback

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_memory_list_new.scss, app/controllers/memory_lists_controller.rb, app/views/components/_composition-builder.html.erb, app/views/compositions/new.html.erb, app/views/memory_lists/new.html.erb
@nibab-boo 
Sorry I forgot to push my changes last time.
=> Composition sandwich

app/controllers/application_controller.rb, app/views/components/_composition-card.html.erb, app/views/components/_compositions-form.html.erb, app/views/components/_instrumentals-index.html.erb, app/views/components/_memory-list-card.html.erb, app/views/components/_memory-list-show.html.erb, app/views/components/_memory-lists-index.html.erb, app/views/memory_lists/show.html.erb
underscore( _ ) removed from file name
=> underscore remover -> underscore_remover('raw_string')

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_loop_checkbox_slider.scss, app/javascript/components/composition_player.js, app/javascript/components/composition_stop_player.js, app/views/compositions/show.html.erb
=> loop button added to player

app/controllers/concerns/speech_api.rb
speech checker to test with Reyona voice
=> speech checking

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_karaoke_score.scss, app/controllers/compositions_controller.rb, app/controllers/concerns/speech_api.rb, app/javascript/components/karaoke.js, app/javascript/components/karaoke_score_popup.js, app/javascript/controllers/index.js, app/javascript/packs/application.js, app/models/composition.rb, app/views/compositions/karaoke.html.erb, db/schema.rb
Karaoke feature still not there but running.
=> Array of sounds

app/javascript/components/composition_player.js, db/schema.rb
=> quick loop fix

app/assets/stylesheets/components/_compositions-new.scss
=> height adjusted on composition new

app/controllers/memory_lists_controller.rb, app/javascript/components/draggable_card_save.js, app/views/memory_lists/new.html.erb
=> Redirect/render for memory_list_new

app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_profile.scss, app/javascript/packs/application.js, app/views/components/_composition-card.html.erb, app/views/shared/_footer.html.erb, app/views/users/profile.html.erb
fixed average on profile
kind of fixed the memory list, its ok now, someone can make it nicer
small css changes
=> Profile review

app/assets/stylesheets/pages/_karaoke_score.scss, app/views/compositions/karaoke.html.erb, app/views/pages/home.html.erb
=> minor changes

app/assets/stylesheets/pages/_karaoke_score.scss
=> height fixed

app/controllers/compositions_controller.rb, app/controllers/users_controller.rb, app/models/composition.rb, app/views/users/profile.html.erb, config/routes.rb
Merge it after merging previous one, please. 
Memorylists associated with current user only available for new user.
=> Memory list fix

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
bootstrapified login and sign up form
=> quick login and sign up fix
